import Head from "next/head";
import React from "react";
import Navbar from "./Navbar";
import About from "./About";
import Community from "./Community";
import Rewards from "./Rewards";
import Dex from "./Dex";
import MarketPlace from "./MarketPlace";
import Footer from "./Footer";

export default function Home() {
  const swiftArray = "Bingo-Token".split("");
  const bingoArray = "Community".split("");

  return (
    <div className="position">
      <Head>
        <title>Bingo</title>
        <meta name="BingoToken Community" content="Generated by MSG.SENDER" />
        <link rel="icon" href="./pics/dexanimate.avif" />
      </Head>

      <Navbar />

      {/* landing page content */}
      <section className="container long">
        <main className="landingwidth">
          <div className="landing">
            <div className="landing-info">
              <div className="landinghead">
                {swiftArray.map((item, index) => {
                  return <span key={index}>{item}</span>;
                })}
              </div>
              <div>
                {bingoArray.map((item, index) => {
                  return (
                    <main className="span" key={index}>
                      {item}
                    </main>
                  );
                })}
              </div>

              <p>
                Birthed by lovers of dogs and crypto currency. Our fun meme
                community aims to spread awareness of animal adoption and
                benefits of crypto currency.
                <br />
                Please explore our page to learn more.
              </p>
            </div>
          </div>

          {/* landing image */}
          <div className="landing-pics">
            <img
              src="./pics/astronaut-01.webp"
              alt="astroBingo"
              className="astroBingo"
            />
          </div>
        </main>
        {/* background waves */}
      </section>
      <div className="waves"></div>

      {/* color switcher */}
      <aside className="switch">
        <form className="color-switcher">
          <fieldset>
            <legend>theme switcher</legend>

            {/* Pink */}
            <label htmlFor="pink" className="visually-hidden">
              System
            </label>
            <input type="radio" name="theme" id="pink" />

            {/* Dark */}
            <label htmlFor="dark" className="visually-hidden">
              Dark
            </label>
            <input type="radio" name="theme" id="dark" />

            {/* system */}
            <label htmlFor="light" className="visually-hidden">
              System
            </label>
            <input type="radio" name="theme" id="light" />
          </fieldset>
        </form>
      </aside>

      <About />

      <Rewards />

      <Dex />

      <MarketPlace />

      <Community />

      <Footer />
    </div>
  );
}
